name: Autoversion

on:
  schedule:
    - cron: '0 0 * * 1'

jobs:
  bump:
    runs-on: ubuntu-slim
    steps:
      - uses: plengauer/autoversion@80cd28fdbf42e4997553fe6e2d338cb1e2e83286 # v4.0.0
        with:
          github_token: ${{ secrets.ACTIONS_GITHUB_TOKEN }}
