name: 'Deploy OpenTelemetry'

on:
  push:
    branches: main
    paths:
      - .github/workflows/**

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: deploy-otel-job-${{ github.ref_name }}
    steps:
      - uses: plengauer/opentelemetry-github/actions/instrument/deploy@215271fe54efbdffbece78b02493f7ecd73678f8 # v5.50.0
        with:
          github_token: ${{ secrets.ACTIONS_GITHUB_TOKEN }}
        env:
          OTEL_EXPORTER_OTLP_ENDPOINT: '${{ secrets.OTEL_EXPORTER_OTLP_ENDPOINT }}'
          OTEL_EXPORTER_OTLP_HEADERS: '${{ secrets.OTEL_EXPORTER_OTLP_HEADERS }}'
