name: 'Deploy OpenTelemetry'

on:
  push:
    branches: main
    paths:
      - .github/workflows/**

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: deploy-otel-job-${{ github.ref_name }}
    steps:
      - uses: plengauer/opentelemetry-github/actions/instrument/deploy@8a42906ace6a618a3b91545ef9b655b8c6d2ac23 # v5.54.0
        with:
          github_token: ${{ secrets.ACTIONS_GITHUB_TOKEN }}
        env:
          OTEL_EXPORTER_OTLP_ENDPOINT: '${{ secrets.OTEL_EXPORTER_OTLP_ENDPOINT }}'
          OTEL_EXPORTER_OTLP_HEADERS: '${{ secrets.OTEL_EXPORTER_OTLP_HEADERS }}'
