name: Autorerun

on:
  workflow_run:
    workflows: ['Update Debian Repository']
    types: completed
  schedule:
    - cron: '0 0 * * *'

concurrency:
  group: rerun-${{ github.event.workflow_run.id }}

jobs:
  rerun:
    runs-on: ubuntu-slim
    steps:
      - uses: plengauer/opentelemetry-github/actions/instrument/job@5bcdcda002db860a69870d21a21bb5d1e5cf64c3 # v5.61.5
        env:
          OTEL_EXPORTER_OTLP_ENDPOINT: ${{ secrets.OTEL_EXPORTER_OTLP_ENDPOINT }}
          OTEL_EXPORTER_OTLP_HEADERS: ${{ secrets.OTEL_EXPORTER_OTLP_HEADERS }}
        with:
          secrets_to_redact: '["${{ github.token }}","${{ secrets.ACTIONS_GITHUB_TOKEN }}"]'
      - uses: plengauer/autorerun@01cbbd02fa9641d3e243b12190be63c7aa3a13c5 # v0.38.0
        with:
          github_token: ${{ secrets.ACTIONS_GITHUB_TOKEN }}
    permissions:
      actions: read
