name: 'Nuke Secrets'

on:
  workflow_dispatch:

jobs:

  list-repositories:
    runs-on: ubuntu-slim
    outputs:
      repositories: ${{ steps.dynamic.outputs.repositories }}
    steps:
      - uses: plengauer/opentelemetry-github/actions/instrument/job@2169fb0fa9a8260fde99a2a185bbf99a5d63546e # v5.59.0
        env:
          OTEL_EXPORTER_OTLP_ENDPOINT: ${{ secrets.OTEL_EXPORTER_OTLP_ENDPOINT }}
          OTEL_EXPORTER_OTLP_HEADERS: ${{ secrets.OTEL_EXPORTER_OTLP_HEADERS }}
        with:
          secrets_to_redact: |-
            ${{ github.token }}
            ${{ secrets.BOT_GITHUB_TOKEN }}
      - id: dynamic
        env:
          GH_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}
        run: |
          gh api /users/${{ github.repository_owner }}/repos --paginate | jq '.[] | select(.fork == false and .visibility == "public" and .owner.login == "${{ github.repository_owner }}") | .name' -r \
            | sort -R | head -n 256 | jq -R | jq '"${{ github.repository_owner }}/" + .' | jq -cs | xargs -0 -I {} echo 'repositories={}' >> "$GITHUB_OUTPUT"
    permissions:
      actions: read

  nuke-secrets:
    needs: list-repositories
    runs-on: ubuntu-slim
    strategy:
      matrix:
        repository: ${{ fromJSON(needs.list-repositories.outputs.repositories) }}
    steps:
      - uses: plengauer/opentelemetry-github/actions/instrument/job@2169fb0fa9a8260fde99a2a185bbf99a5d63546e # v5.59.0
        env:
          OTEL_EXPORTER_OTLP_ENDPOINT: ${{ secrets.OTEL_EXPORTER_OTLP_ENDPOINT }}
          OTEL_EXPORTER_OTLP_HEADERS: ${{ secrets.OTEL_EXPORTER_OTLP_HEADERS }}
        with:
          secrets_to_redact: |-
            ${{ github.token }}
            ${{ secrets.BOT_GITHUB_TOKEN }}
      - env:
          GH_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}
        run: |
          gh secret delete ACTIONS_GITHUB_TOKEN --repo ${{ matrix.repository }} || true
          gh secret delete COPILOT_GITHUB_TOKEN --repo ${{ matrix.repository }} || true
          gh secret delete OTEL_EXPORTER_OTLP_ENDPOINT --repo ${{ matrix.repository }} || true
          gh secret delete OTEL_EXPORTER_OTLP_HEADERS --repo ${{ matrix.repository }} || true
          curl --fail --no-progress-meter -H 'Authorization: Bearer ${{ secrets.BOT_GITHUB_TOKEN }}' https://api.github.com/repos/${{ matrix.repository }}/environments'?per_page=100' | jq '.environments[].name' -r | while read -r environment; do
            gh secret delete OTEL_EXPORTER_OTLP_ENDPOINT --repo ${{ matrix.repository }} --env "$environment" || true
            gh secret delete OTEL_EXPORTER_OTLP_HEADERS --repo ${{ matrix.repository }} --env "$environment" || true
          done
    permissions:
      actions: read
