
name: OpenTelemetry
on:
  workflow_run:
    workflows:
      - .github/workflows/copilot-setup-steps.yml
      - Autobackport
      - Autofix Failed Templates
      - Autorerun
      - Autotriage
      - Autoversion
      - Claude
      - CodeQL
      - Copilot
      - Copilot cloud agent
      - Copilot code review
      - Nuke Secrets
      - Onboard
      - OpenAI Codex
      - Recompile Agentic Workflows
      - Renovate
      - Update Package Repository
      - pages-build-deployment
    types:
      - completed
jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - uses: plengauer/opentelemetry-github/actions/instrument/workflow@5bcdcda002db860a69870d21a21bb5d1e5cf64c3 # v5.61.5
        env:
          OTEL_EXPORTER_OTLP_ENDPOINT: ${{ secrets.OTEL_EXPORTER_OTLP_ENDPOINT }}
          OTEL_EXPORTER_OTLP_HEADERS: ${{ secrets.OTEL_EXPORTER_OTLP_HEADERS }}
    permissions:
      actions: read
    container: ghcr.io/plengauer/opentelemetry-github-workflow-instrumentation-runner:v5.61.5
