name: Onboard

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/onboard.yml
      - .github/template/**
  schedule:
    - cron: '0 0 * * *'

concurrency:
  group: onboard

jobs:

  list-repositories:
    runs-on: ubuntu-slim
    outputs:
      repositories: ${{ steps.dynamic.outputs.repositories }}
    steps:
      - uses: plengauer/opentelemetry-github/actions/instrument/job@909c7153cce2c6ef916f4fde6958886d9d65af03 # v5.55.0
        env:
          OTEL_EXPORTER_OTLP_ENDPOINT: ${{ secrets.OTEL_EXPORTER_OTLP_ENDPOINT }}
          OTEL_EXPORTER_OTLP_HEADERS: ${{ secrets.OTEL_EXPORTER_OTLP_HEADERS }}
        with:
          secrets_to_redact: |-
            ${{ github.token }}
            ${{ secrets.BOT_GITHUB_TOKEN }}
      - id: dynamic
        env:
          GH_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}
        run: |
          gh api /users/${{ github.repository_owner }}/repos --paginate | jq '.[] | select(.fork == false and .visibility == "public" and .owner.login == "${{ github.repository_owner }}") | .name' -r \
            | sort -R | head -n 256 | jq -R | jq '"${{ github.repository_owner }}/" + .' | jq -cs | xargs -0 -I {} echo 'repositories={}' >> "$GITHUB_OUTPUT"
    permissions:
      actions: read

  deploy-codescanning:
    needs: list-repositories
    runs-on: ubuntu-slim
    strategy:
      matrix:
        repository: ${{ fromJSON(needs.list-repositories.outputs.repositories) }}
      fail-fast: false
    steps:
      - uses: plengauer/opentelemetry-github/actions/instrument/job@909c7153cce2c6ef916f4fde6958886d9d65af03 # v5.55.0
        env:
          OTEL_EXPORTER_OTLP_ENDPOINT: ${{ secrets.OTEL_EXPORTER_OTLP_ENDPOINT }}
          OTEL_EXPORTER_OTLP_HEADERS: ${{ secrets.OTEL_EXPORTER_OTLP_HEADERS }}
        with:
          secrets_to_redact: |-
            ${{ github.token }}
            ${{ secrets.BOT_GITHUB_TOKEN }}
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - run: |
          case "$(curl -s --fail --header "Authorization: Bearer ${{ secrets.BOT_GITHUB_TOKEN }}" https://api.github.com/repos/${{ matrix.repository }}/code-scanning/default-setup | jq .state -r)" in
            configured) curl -s --fail --header "Authorization: Bearer ${{ secrets.BOT_GITHUB_TOKEN }}" https://api.github.com/repos/${{ matrix.repository }}/code-scanning/default-setup | jq 'del(.schedule) | del(.updated_at)' > code_scanning.json;;
            not-configured)
              if curl -s --fail --header "Authorization: Bearer ${{ secrets.BOT_GITHUB_TOKEN }}" https://api.github.com/repos/${{ matrix.repository }}/code-scanning/analyses'?per_page=1' > /dev/null; then exit 0; fi
              cp ./.github/template/code_scanning.json code_scanning.json
              ;;
            *) exit 1;;
          esac
          curl -s --fail-with-body --header "Authorization: Bearer ${{ secrets.BOT_GITHUB_TOKEN }}" https://api.github.com/repos/${{ matrix.repository }}/languages | jq 'to_entries[].key' -r | tr '[:upper:]' '[:lower:]' > languages.list
          cat ./.github/template/code_scanning.json code_scanning.json | jq -s '.[0].languages = .[1].languages | .[0]' > tmp.json && cp tmp.json code_scanning.json && rm tmp.json
          jq < code_scanning.json '.languages[]' -r | while read -r language; do
            if [ "$language" = actions ]; then
              curl -s --fail-with-body --header "Authorization: Bearer ${{ secrets.BOT_GITHUB_TOKEN }}" https://api.github.com/repos/${{ matrix.repository }}/contents/.github/workflows | jq .[].name -r | grep -q '.yml$'
            else
              grep -qF '^'"$language"'$' languages.list
            fi || ( jq < code_scanning.json 'del(.languages[] | select(. == "'"$language"'" or startswith("'"$language"'-") or endswith("-'"$language"'") or contains("-'"$language"'-")))' > tmp.json && cp tmp.json code_scanning.json && rm tmp.json )
          done
          curl -s --fail-with-body --header "Authorization: Bearer ${{ secrets.BOT_GITHUB_TOKEN }}" https://api.github.com/repos/${{ matrix.repository }}/code-scanning/default-setup -d @./code_scanning.json -X PATCH
    permissions:
      actions: read

  deploy-ruleset:
    needs: [ list-repositories, deploy-codescanning ]
    runs-on: ubuntu-slim
    strategy:
      matrix:
        repository: ${{ fromJSON(needs.list-repositories.outputs.repositories) }}
      fail-fast: false
    steps:
      - uses: plengauer/opentelemetry-github/actions/instrument/job@909c7153cce2c6ef916f4fde6958886d9d65af03 # v5.55.0
        env:
          OTEL_EXPORTER_OTLP_ENDPOINT: ${{ secrets.OTEL_EXPORTER_OTLP_ENDPOINT }}
          OTEL_EXPORTER_OTLP_HEADERS: ${{ secrets.OTEL_EXPORTER_OTLP_HEADERS }}
        with:
          secrets_to_redact: |-
            ${{ github.token }}
            ${{ secrets.BOT_GITHUB_TOKEN }}
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - run: |
          [ "$(curl -s --fail --header "Authorization: Bearer ${{ secrets.BOT_GITHUB_TOKEN }}" https://api.github.com/repos/${{ matrix.repository }}/rulesets | jq length)" = 0 ] || exit 0
          curl -s --fail-with-body --header "Authorization: Bearer ${{ secrets.BOT_GITHUB_TOKEN }}" https://api.github.com/repos/${{ matrix.repository }} -d @./.github/template/settings.json -X PATCH
          curl -s --fail-with-body --header "Authorization: Bearer ${{ secrets.BOT_GITHUB_TOKEN }}" https://api.github.com/repos/${{ matrix.repository }}/rulesets -d @./.github/template/rulesets.json
    permissions:
      actions: read
  adjust-ruleset:
    needs: [ list-repositories, deploy-ruleset ]
    runs-on: ubuntu-slim
    strategy:
      matrix:
        repository: ${{ fromJSON(needs.list-repositories.outputs.repositories) }}
      fail-fast: false
    steps:
      - uses: plengauer/opentelemetry-github/actions/instrument/job@909c7153cce2c6ef916f4fde6958886d9d65af03 # v5.55.0
        env:
          OTEL_EXPORTER_OTLP_ENDPOINT: ${{ secrets.OTEL_EXPORTER_OTLP_ENDPOINT }}
          OTEL_EXPORTER_OTLP_HEADERS: ${{ secrets.OTEL_EXPORTER_OTLP_HEADERS }}
        with:
          secrets_to_redact: '["${{ github.token }}","${{ secrets.BOT_GITHUB_TOKEN }}"]'
      - env:
          GH_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}
        run: |
          collaborator_count="$(gh api /repos/${{ matrix.repository }}/collaborators --paginate | jq length)"
          gh api /repos/${{ matrix.repository }}/rulesets --paginate | jq '.[].id' | while read -r id; do
            gh api /repos/${{ matrix.repository }}/rulesets/"$id" > ruleset.json
            if [ "$collaborator_count" -gt 1 ]; then
              if [ "$(jq < ruleset.json '.rules[] | select(.type == "pull_request") | .parameters.required_approving_review_count')" = 0 ]; then
                jq < ruleset.json '.rules |= map(if .type == "pull_request" then .parameters.required_approving_review_count = 1 else . end)' > tmp.json && cat < tmp.json > ruleset.json && rm tmp.json
              fi
              jq < ruleset.json '.rules |= map(if .type == "pull_request" then .parameters.require_last_push_approval = true else . end)' > tmp.json && cat < tmp.json > ruleset.json && rm tmp.json
              jq < ruleset.json '.rules |= map(if .type == "pull_request" then .parameters.require_code_owner_review = true else . end)' > tmp.json && cat < tmp.json > ruleset.json && rm tmp.json
            elif [ "$collaborator_count" = 1 ]; then
              jq < ruleset.json '.rules |= map(if .type == "pull_request" then .parameters.required_approving_review_count = 0 else . end)' > tmp.json && cat < tmp.json > ruleset.json && rm tmp.json
              jq < ruleset.json '.rules |= map(if .type == "pull_request" then .parameters.require_last_push_approval = false else . end)' > tmp.json && cat < tmp.json > ruleset.json && rm tmp.json
              jq < ruleset.json '.rules |= map(if .type == "pull_request" then .parameters.require_code_owner_review = false else . end)' > tmp.json && cat < tmp.json > ruleset.json && rm tmp.json
            fi
            if [ "$(jq < ruleset.json '.rules[] | select(.type == "pull_request") | .parameters.required_approving_review_count')" -gt $((collaborator_count - 1)) ]; then
              jq < ruleset.json '.rules |= map(if .type == "pull_request" then .parameters.required_approving_review_count = '$((collaborator_count - 1))' else . end)' > tmp.json && cat < tmp.json > ruleset.json && rm tmp.json
            fi
            jq < ruleset.json '{ "name": .name, "target": .target, "enforcement": .enforcement, "bypass_actors": .bypass_actors, "conditions": .conditions, "rules": .rules }' \
              | curl -s --fail-with-body --header "Authorization: Bearer $GH_TOKEN" https://api.github.com/repos/${{ matrix.repository }}/rulesets/"$id" -d @- -X PUT
          done
    permissions:
      actions: read

  deploy-codeowners:
    needs: [ list-repositories, deploy-ruleset, deploy-codescanning ]
    runs-on: ubuntu-slim
    strategy:
      matrix: 
        repository: ${{ fromJSON(needs.list-repositories.outputs.repositories) }}
      fail-fast: false
    steps:
      - uses: plengauer/opentelemetry-github/actions/instrument/job@909c7153cce2c6ef916f4fde6958886d9d65af03 # v5.55.0
        env:
          OTEL_EXPORTER_OTLP_ENDPOINT: ${{ secrets.OTEL_EXPORTER_OTLP_ENDPOINT }}
          OTEL_EXPORTER_OTLP_HEADERS: ${{ secrets.OTEL_EXPORTER_OTLP_HEADERS }}
        with:
          secrets_to_redact: '["${{ github.token }}","${{ secrets.BOT_GITHUB_TOKEN }}"]'
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          repository: ${{ matrix.repository }}
          token: ${{ secrets.BOT_GITHUB_TOKEN }}
      - run: |
          [ -r .github/CODEOWNERS ] || ( mkdir -p .github && echo '* @${{ github.repository_owner }}' > .github/CODEOWNERS )
      - uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        id: open-pr
        with:
          token: ${{ secrets.BOT_GITHUB_TOKEN }}
          commit-message: "Onboard codeowners"
          branch: "automate-onboard-codeowners"
          title: "Onboard codeowners"
          delete-branch: true
      - run: sleep 60
        if: steps.open-pr.outputs.pull-request-number != null
      - uses: peter-evans/enable-pull-request-automerge@a660677d5469627102a1c1e11409dd063606628d # v3.0.0
        if: steps.open-pr.outputs.pull-request-number != null
        with:
          token: ${{ secrets.BOT_GITHUB_TOKEN }}
          repository: ${{ matrix.repository }}
          pull-request-number: ${{ steps.open-pr.outputs.pull-request-number }}
          merge-method: squash
    permissions:
      actions: read

  list-actions:
    runs-on: ubuntu-slim
    outputs:
      actions: ${{ steps.dynamic.outputs.actions }}
    steps:
      - uses: plengauer/opentelemetry-github/actions/instrument/job@909c7153cce2c6ef916f4fde6958886d9d65af03 # v5.55.0
        env:
          OTEL_EXPORTER_OTLP_ENDPOINT: ${{ secrets.OTEL_EXPORTER_OTLP_ENDPOINT }}
          OTEL_EXPORTER_OTLP_HEADERS: ${{ secrets.OTEL_EXPORTER_OTLP_HEADERS }}
        with:
          secrets_to_redact: '["${{ github.token }}"]'
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - run: |
          ls .github/template | while read -r automation; do [ -d .github/template/"$automation" ] && echo "$automation" || true; done | jq -R | jq -cs | xargs -0 -I {} echo 'actions={}' >> "$GITHUB_OUTPUT"
        id: dynamic
    permissions:
      actions: read
  deploy-action:
    needs: [ list-repositories, list-actions, deploy-ruleset, deploy-codescanning, deploy-gh-token, deploy-otel-token ]
    runs-on: ubuntu-slim
    strategy:
      matrix:
        repository: ${{ fromJSON(needs.list-repositories.outputs.repositories) }}
        action: ${{ fromJSON(needs.list-actions.outputs.actions) }}
      fail-fast: false
    steps:
      - uses: plengauer/opentelemetry-github/actions/instrument/job@909c7153cce2c6ef916f4fde6958886d9d65af03 # v5.55.0
        env:
          OTEL_EXPORTER_OTLP_ENDPOINT: ${{ secrets.OTEL_EXPORTER_OTLP_ENDPOINT }}
          OTEL_EXPORTER_OTLP_HEADERS: ${{ secrets.OTEL_EXPORTER_OTLP_HEADERS }}
        with:
          secrets_to_redact: '["${{ github.token }}","${{ secrets.BOT_GITHUB_TOKEN }}"]'
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          token: ${{ secrets.BOT_GITHUB_TOKEN }}
          path: ./self
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          token: ${{ secrets.BOT_GITHUB_TOKEN }}
          path: ./other
          repository: ${{ matrix.repository }}
      - id: check
        run: |
          path=./self/.github/template/${{ matrix.action }}.check
          [ -x "$path" ] || ! [ -r "$path" ] || exit 0
          ( ! [ -x "$path" ] || GITHUB_REPOSITORY="${{ matrix.repository }}" GITHUB_TOKEN="${{ github.token }}" eval "$path" ./other ) && echo deploy=true >> "$GITHUB_OUTPUT" || true
      - if: steps.check.outputs.deploy == 'true'
        run: |
          find "$(pwd)"/self/.github/template/${{ matrix.action }} | while read -r file; do
            if [ -d "$file" ]; then continue; fi
            new_file=./other/"${file#*/self/.github/template/${{ matrix.action }}/}"
            [ -f "$new_file" ] || [ -f "${new_file//yml/yaml}" ] || (mkdir -p "${new_file%/*}" && cp "$file" "$new_file")
          done
      - uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        id: open-pr
        with:
          token: ${{ secrets.BOT_GITHUB_TOKEN }}
          path: ./other
          commit-message: "Onboard action ${{ matrix.action }}"
          branch: "automate-onboard-action-${{ matrix.action }}"
          title: "Onboard action ${{ matrix.action }}"
          delete-branch: true
      - run: sleep 60
        if: steps.open-pr.outputs.pull-request-number != null
      - uses: peter-evans/enable-pull-request-automerge@a660677d5469627102a1c1e11409dd063606628d # v3.0.0
        if: steps.open-pr.outputs.pull-request-number != null
        with:
          token: ${{ secrets.BOT_GITHUB_TOKEN }}
          repository: ${{ matrix.repository }}
          pull-request-number: ${{ steps.open-pr.outputs.pull-request-number }}
          merge-method: squash
    permissions:
      actions: read

  maintain-gh-cookie:
    runs-on: ubuntu-slim
    steps:
      - uses: plengauer/opentelemetry-github/actions/instrument/job@909c7153cce2c6ef916f4fde6958886d9d65af03 # v5.55.0
        env:
          OTEL_EXPORTER_OTLP_ENDPOINT: ${{ secrets.OTEL_EXPORTER_OTLP_ENDPOINT }}
          OTEL_EXPORTER_OTLP_HEADERS: ${{ secrets.OTEL_EXPORTER_OTLP_HEADERS }}
        with:
          secrets_to_redact: |-
            ${{ github.token }}
            ${{ secrets.BOT_GITHUB_TOKEN }}
            ${{ secrets.GH_COOKIE }}
      - run: |
          tr <<< '${{ secrets.GH_COOKIE }}' -d ' ' | tr ';' '\n' > cookies
          curl -v https://github.com/ --header 'cookie: ${{ secrets.GH_COOKIE }}' 2>&1 1> /dev/null \
            | grep -E '^< set-cookie: ' | cut -d ' ' -f 3- | cut -d ';' -f 1 | while read -r cookie; do
              sed -i 's/^'"${cookie%%=*}"'=.*$/'"$cookie"'/g' cookies
              touch modified
            done
          if [ -r modified ]; then
            tr < cookies '\n' ';' | sed 's/;/; /g' | GH_TOKEN=${{ secrets.BOT_GITHUB_TOKEN }} gh secret set GH_COOKIE --repo ${{ github.repository }}
          fi
          rm cookies
    permissions:
      actions: read
  deploy-gh-token:
    needs: [ list-repositories, maintain-gh-cookie ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repository: ${{ fromJSON(needs.list-repositories.outputs.repositories) }}
      fail-fast: true
      max-parallel: 1 # 3
    steps:
      - uses: plengauer/opentelemetry-github/actions/instrument/job@909c7153cce2c6ef916f4fde6958886d9d65af03 # v5.55.0
        env:
          OTEL_EXPORTER_OTLP_ENDPOINT: ${{ secrets.OTEL_EXPORTER_OTLP_ENDPOINT }}
          OTEL_EXPORTER_OTLP_HEADERS: ${{ secrets.OTEL_EXPORTER_OTLP_HEADERS }}
        with:
          secrets_to_redact: |-
            ${{ github.token }}
            ${{ secrets.BOT_GITHUB_TOKEN }}
            ${{ secrets.GH_COOKIE }}
            ${{ secrets.GH_PASSWORD }}
            ${{ secrets.OPENAI_TOKEN }}
      - run: |
          repository="${{ matrix.repository }}"
          [ "${repository%%/*}" = plengauer ] # as long as one cannot create fine grained tokens for other repos, we should restrict for safety reasons
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - id: metadata
        run: |
          repository='${{ matrix.repository }}'
          echo token_name="GitHub Actions $(echo "${repository#*/} ${{ github.run_id }} ${{ github.run_attempt }}" | md5sum | cut -d - -f 1 | tr -d ' ')" >> "$GITHUB_OUTPUT"
          jq < .github/template/token_permissions.json 'to_entries | .[] | .key + "=" + .value' -r | perl -p -e 'chomp if eof' | tr '\n' ',' | xargs -I '{}' echo token_permissions='{}' >> "$GITHUB_OUTPUT"
          xargs < .github/template/token_retention.days -I '{}' echo token_retention='{}' >> "$GITHUB_OUTPUT"
      - id: resolve
        run: |
          created_at="$( ( curl --fail --no-progress-meter -H 'Authorization: Bearer ${{ secrets.BOT_GITHUB_TOKEN }}' https://api.github.com/repos/${{ matrix.repository }}/actions/secrets/ACTIONS_GITHUB_TOKEN || echo '{ "updated_at": "1970-01-01" }' ) | jq .updated_at -r)"
          ( [ $(( $(date +%s) - $(date +%s -d "$created_at") )) -gt $((60 * 60 * 24 * ${{ steps.metadata.outputs.token_retention }} * 80 / 100)) ] && echo true || echo false ) | xargs -0 -I '{}' echo rotate='{}' >> "$GITHUB_OUTPUT"
      - if: ${{ steps.resolve.outputs.rotate == 'true' }}
        id: create
        uses: plengauer/create-github-finegrained-pat@v0.8.0
        with:
          name: ${{ steps.metadata.outputs.token_name }}
          expiration: ${{ steps.metadata.outputs.token_retention }}
          repositories: ${{ matrix.repository }}
          permissions: ${{ steps.metadata.outputs.token_permissions }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_PASSWORD }}
          cookie: ${{ secrets.GH_COOKIE }}
          openai_api_token: ${{ secrets.OPENAI_TOKEN }}
        env:
          OPENAI_MODEL: gpt-5.3-codex
          OPENAI_SERVICE_TIER: default
          OPENAI_REASONING_EFFORT: xhigh
      - if: ${{ success() && steps.resolve.outputs.rotate == 'true' }}
        run: |
          GH_TOKEN=${{ secrets.BOT_GITHUB_TOKEN }} gh secret set ACTIONS_GITHUB_TOKEN --repo ${{ matrix.repository }} < "${{ steps.create.outputs.token_path }}"
          GH_TOKEN=${{ secrets.BOT_GITHUB_TOKEN }} gh secret set COPILOT_GITHUB_TOKEN --repo ${{ matrix.repository }} < "${{ steps.create.outputs.token_path }}"
    permissions:
      actions: read

  deploy-otel-token:
    needs: list-repositories
    runs-on: ubuntu-slim
    strategy:
      matrix:
        repository: ${{ fromJSON(needs.list-repositories.outputs.repositories) }}
      fail-fast: false
    steps:
      - uses: plengauer/opentelemetry-github/actions/instrument/job@909c7153cce2c6ef916f4fde6958886d9d65af03 # v5.55.0
        env:
          OTEL_EXPORTER_OTLP_ENDPOINT: ${{ secrets.OTEL_EXPORTER_OTLP_ENDPOINT }}
          OTEL_EXPORTER_OTLP_HEADERS: ${{ secrets.OTEL_EXPORTER_OTLP_HEADERS }}
        with:
          secrets_to_redact: '["${{ github.token }}","${{ secrets.BOT_DT_TOKEN }}","${{ secrets.BOT_GITHUB_TOKEN }}","${{ secrets.OTEL_EXPORTER_OTLP_ENDPOINT }}"]'
      - run: |
          curl --fail --no-progress-meter -H 'Authorization: Bearer ${{ secrets.BOT_GITHUB_TOKEN }}' https://api.github.com/repos/${{ matrix.repository }}/actions/secrets/OTEL_EXPORTER_OTLP_ENDPOINT || GH_TOKEN=${{ secrets.BOT_GITHUB_TOKEN }} gh secret set OTEL_EXPORTER_OTLP_ENDPOINT --repo ${{ matrix.repository }} <<< '${{ vars.DYNATRACE_TENANT }}/api/v2/otlp'
          curl --fail --no-progress-meter -H 'Authorization: Bearer ${{ secrets.BOT_GITHUB_TOKEN }}' https://api.github.com/repos/${{ matrix.repository }}/environments'?per_page=100' | jq '.environments[].name' -r | while read -r environment; do
            curl --fail --no-progress-meter -H 'Authorization: Bearer ${{ secrets.BOT_GITHUB_TOKEN }}' https://api.github.com/repos/${{ matrix.repository }}/environments/"$environment"/secrets/OTEL_EXPORTER_OTLP_ENDPOINT || GH_TOKEN=${{ secrets.BOT_GITHUB_TOKEN }} gh secret set OTEL_EXPORTER_OTLP_ENDPOINT --repo ${{ matrix.repository }} --env "$environment" <<< '${{ vars.DYNATRACE_TENANT }}/api/v2/otlp'
          done
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - run: |
          retention_days="$(cat .github/template/token_retention.days)"
          endpoint=${{ secrets.OTEL_EXPORTER_OTLP_ENDPOINT }}
          created_at="$( ( curl --fail --no-progress-meter -H 'Authorization: Bearer ${{ secrets.BOT_GITHUB_TOKEN }}' https://api.github.com/repos/${{ matrix.repository }}/actions/secrets/OTEL_EXPORTER_OTLP_HEADERS || echo '{ "updated_at": "1970-01-01" }' ) | jq .updated_at -r)"
          [ $(( $(date +%s) - $(date +%s -d "$created_at") )) -le $((60 * 60 * 24 * $retention_days * 80 / 100)) ] || curl --fail --no-progress-meter -H 'Authorization: Api-Token ${{ secrets.BOT_DT_TOKEN }}' -H 'Content-type: application/json' '${{ vars.DYNATRACE_TENANT }}'/api/v2/apiTokens -d @- << EOF | jq .token -r | xargs -0 -I '{}' echo "authorization=Api-Token {}" | GH_TOKEN=${{ secrets.BOT_GITHUB_TOKEN }} gh secret set OTEL_EXPORTER_OTLP_HEADERS --repo ${{ matrix.repository }}
          {
            "name": "GitHub ${{ matrix.repository }}",
            "personalAccessToken": false,
            "scopes": [
              "logs.ingest",
              "metrics.ingest",
              "openTelemetryTrace.ingest"
            ],
            "expirationDate": "now+${retention_days}d"
          }
          EOF
          curl --fail --no-progress-meter -H 'Authorization: Bearer ${{ secrets.BOT_GITHUB_TOKEN }}' https://api.github.com/repos/${{ matrix.repository }}/environments'?per_page=100' | jq '.environments[].name' -r | while read -r environment; do
            created_at="$( ( curl --fail --no-progress-meter -H 'Authorization: Bearer ${{ secrets.BOT_GITHUB_TOKEN }}' https://api.github.com/repos/${{ matrix.repository }}/environments/"$environment"/secrets/OTEL_EXPORTER_OTLP_HEADERS || echo '{ "updated_at": "1970-01-01" }' ) | jq .updated_at -r)"
            [ $(( $(date +%s) - $(date +%s -d "$created_at") )) -le $((60 * 60 * 24 * $retention_days * 80 / 100)) ] || curl --fail --no-progress-meter -H 'Authorization: Api-Token ${{ secrets.BOT_DT_TOKEN }}' -H 'Content-type: application/json' '${{ vars.DYNATRACE_TENANT }}'/api/v2/apiTokens -d @- << EOF | jq .token -r | xargs -0 -I '{}' echo "authorization=Api-Token {}" | GH_TOKEN=${{ secrets.BOT_GITHUB_TOKEN }} gh secret set OTEL_EXPORTER_OTLP_HEADERS --repo ${{ matrix.repository }} --env "$environment"
          {
            "name": "GitHub ${{ matrix.repository }} $environment",
            "personalAccessToken": false,
            "scopes": [
              "logs.ingest",
              "metrics.ingest",
              "openTelemetryTrace.ingest"
            ],
            "expirationDate": "now+${retention_days}d"
          }
          EOF
          done
    permissions:
      actions: read
