name: 'Update Index'

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - main
    paths:
      - .github/workflows/update_index.yml
  workflow_dispatch:

concurrency:
  group: update

jobs:

  list-repositories:
    runs-on: ubuntu-slim
    outputs:
      repositories: ${{ steps.dynamic.outputs.repositories }}
    steps:
      - id: dynamic
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh api /users/${{ github.repository_owner }}/repos --paginate | jq '.[] | select(.visibility == "public") | .name' | sort -R | head -n 256 | jq -sc | xargs -0 -I '{}' echo repositories='{}' >> "$GITHUB_OUTPUT"

  scrape-repository:
    needs: list-repositories
    runs-on: ubuntu-slim
    strategy:
      matrix:
        repository: ${{ fromJSON(needs.list-repositories.outputs.repositories) }}
      fail-fast: false
    steps:
      - env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh api /repos/${{ github.repository_owner }}/${{ matrix.repository }}/releases --paginate | jq '.[] | .assets[] | select(.name | endswith(".deb")) | { "repository": "${{ matrix.repository }}", "id": .id, "digest": .digest }' -rc > assets.json
      - uses: actions/upload-artifact@v6.0.0
        with:
          name: 'assets-${{ matrix.repository }}'
          path: assets.json

  setup-generate-entries:
    needs: scrape-repository
    runs-on: ubuntu-slim
    outputs:
      jobs: ${{ steps.dynamic.outputs.jobs }}
    steps:
      - uses: actions/checkout@v6.0.0
      - uses: actions/download-artifact@v7.0.0
        with:
          pattern: 'assets-*'
      - id: dynamic
        run: |
          grep < apt/dists/stable/main/binary-all/Packages '^SHA|^MD5sum' | tr '[:upper:]' '[:lower:]' | tr -d ' ' > index.list || true
          find . -name 'assets.json' -exec cat '{}' + | jq -c | grep -v -f index.list | sort -R | head -n 256 | jq -sc | xargs -0 -I '{}' echo jobs='{}' >> "$GITHUB_OUTPUT"

  generate-entry:
    needs: setup-generate-entries
    if: ${{ needs.setup-generate-entries.outputs.jobs != '[]' }}
    runs-on: ubuntu-slim
    strategy:
      matrix:
        include: ${{ fromJSON(needs.setup-generate-entries.outputs.jobs) }}
    steps:
      - run: |
          url="${GITHUB_API_URL:-https://api.github.com}"/repos/${{ github.repository_owner }}/${{ matrix.repository }}/releases/assets/${{ matrix.id }}
          wget --header 'Authorization: Bearer ${{ github.token }}' --header 'Accept: application/octet-stream' -nc -O ./${{ matrix.id }}.deb "$url"
          url="$(curl -s --fail --header "Authorization: Bearer ${{ github.token }}" "$url" | jq '.browser_download_url' -r)"
          dpkg-scanpackages --multiversion ./${{ matrix.id }}.deb | while read -r line; do
            case "$line" in
              'Filename:'*) echo "Filename: $url";;
              *) echo "$line";;
            esac
          done > Packages.part
      - uses: actions/upload-artifact@v6.0.0
        with:
          name: 'packages.part-${{ matrix.repository }}-${{ matrix.id }}'
          path: Packages.part

  update-index:
    needs: generate-entry
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@v6.0.0
      - uses: actions/download-artifact@v7.0.0
        with:
          pattern: 'packages.part-*'
      - run: mkdir -p apt/dists/stable/main/binary-all/
      - run: ls | grep '^packages.part-' | while read -r directory; do cat < "$directory"/Packages.part; done >> apt/dists/stable/main/binary-all/Packages
      - run: gzip -9 < apt/dists/stable/main/binary-all/Packages > apt/dists/stable/main/binary-all/Packages.gz
      - run: |
          cd apt/dists/stable
          
          do_hash() {
            HASH_NAME=$1
            HASH_CMD=$2
            echo "${HASH_NAME}:"
            for f in $(find -type f); do
                f=$(echo $f | cut -c3-) # remove ./ prefix
                if [ "$f" = "Release" ]; then
                    continue
                fi
                echo " $(${HASH_CMD} ${f}  | cut -d" " -f1) $(wc -c $f)"
            done
          }
          
          cat > Release << EOF
          Origin: GitHub ${{ github.repository_owner }} Repistory
          Label: GitHub plengauer
          Suite: stable
          Codename: stable
          Version: 1.0
          Architectures: all
          Components: main
          Description: A software repository hosting packages from github
          Date: $(date -Ru)
          EOF
          do_hash "MD5Sum" "md5sum" >> Release
          do_hash "SHA1" "sha1sum" >> Release
          do_hash "SHA256" "sha256sum" >> Release
      - run: ls | grep '^packages.part-' | xargs rm -rf
      - uses: peter-evans/create-pull-request@v8.0.0
        id: open-pr
        with:
          token: ${{ secrets.ACTIONS_GITHUB_TOKEN }}
          commit-message: "Update Index"
          branch: "update-index"
          title: "Update Index"
          delete-branch: true
      - run: sleep 60
        if: steps.open-pr.outputs.pull-request-number != null
      - uses: peter-evans/enable-pull-request-automerge@v3.0.0
        if: steps.open-pr.outputs.pull-request-number != null
        with:
          token: ${{ secrets.ACTIONS_GITHUB_TOKEN }}
          pull-request-number: ${{ steps.open-pr.outputs.pull-request-number }}
          merge-method: squash
