name: 'Update Debian Repository'

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - main
    paths:
      - .github/workflows/update_deb_repository.yml

concurrency:
  group: update

jobs:

  update:
    runs-on: ubuntu-latest
    permissions:
      actions: read
    steps:
      - uses: plengauer/opentelemetry-github/actions/instrument/job@v5.42.0
        env:
          OTEL_EXPORTER_OTLP_ENDPOINT: ${{ secrets.OTEL_EXPORTER_OTLP_ENDPOINT }}
          OTEL_EXPORTER_OTLP_HEADERS: ${{ secrets.OTEL_EXPORTER_OTLP_HEADERS }}
        with:
          secrets_to_redact: '["${{ github.token }}","${{ secrets.ACTIONS_GITHUB_TOKEN }}"]'
      - uses: actions/checkout@v6.0.1
      - id: list-repositories
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh api /users/${{ github.repository_owner }}/repos --paginate | jq '.[] | select(.visibility == "public" and .owner.login == "${{ github.repository_owner }}") | .owner.login + "/" + .name' -r | tr '\n' ' ' | xargs -0 -I '{}' echo repositories='{}' >> "$GITHUB_OUTPUT"
      - run: |
          mkdir -p dists/stable/main/binary-all
          tr <<< "${{ steps.list-repositories.outputs.repositories }}" ' ' '\n' | cut -d / -f 2 | while read -r repository; do
            curl --fail --retry 16 https://${{ github.repository_owner }}.github.io/"$repository"/dists/stable/main/binary-all/Packages | sed 's~^Filename: pool/main/~Filename: '"${repository#*/}"'/pool/main/~g' || true
          done > dists/stable/main/binary-all/Packages
      - id: check
        run: |
          [ "$(git status --porcelain -- dists/stable/main/binary-all/Packages | wc -l)" -gt 0 ] && echo create=true >> "$GITHUB_OUTPUT" || true
      - if: ${{ steps.check.outputs.create == 'true' }}
        uses: plengauer/create-deb-repository@v0.0.17
        with:
          mode: append
          source: ''
      - id: open-pr
        uses: peter-evans/create-pull-request@v8.0.0
        with:
          token: ${{ secrets.ACTIONS_GITHUB_TOKEN }}
          commit-message: "Update Debian Repository"
          base: main
          branch: "update-debian-repository"
          title: "Update Debian Repository"
          body: |
            (this PR is automatically generated)
          delete-branch: true
      - if: steps.open-pr.outputs.pull-request-number != null
        run: sleep 60 # make sure PR state is updated and API can catch up
      - if: steps.open-pr.outputs.pull-request-number != null
        env:
          GH_TOKEN: ${{ secrets.ACTIONS_GITHUB_TOKEN }}
        run: gh pr merge --squash --auto ${{ steps.open-pr.outputs.pull-request-number }}
