name: 'Update Debian Repository'

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - main
    paths:
      - .github/workflows/update_deb_repository.yml

concurrency:
  group: update

jobs:

  update:
    runs-on: ubuntu-latest
    permissions:
      actions: read
    steps:
      - uses: plengauer/opentelemetry-github/actions/instrument/job@v5.47.3
        env:
          OTEL_EXPORTER_OTLP_ENDPOINT: ${{ secrets.OTEL_EXPORTER_OTLP_ENDPOINT }}
          OTEL_EXPORTER_OTLP_HEADERS: ${{ secrets.OTEL_EXPORTER_OTLP_HEADERS }}
        with:
          secrets_to_redact: '["${{ github.token }}","${{ secrets.ACTIONS_GITHUB_TOKEN }}"]'
      - uses: actions/checkout@v6.0.2
      - id: list-repositories
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh api /users/${{ github.repository_owner }}/repos --paginate | jq '.[] | select(.visibility == "public" and .owner.login == "${{ github.repository_owner }}") | .owner.login + "/" + .name | select(. != "${{ github.repository }}")' -r | tr '\n' ' ' | xargs -0 -I '{}' echo repositories='{}' >> "$GITHUB_OUTPUT"
      - run: |
          { echo all; dpkg-architecture -L | grep -v -- -; } | while read -r arch; do
            mkdir -p dists/stable/main/binary-"$arch"
            tr <<< "${{ steps.list-repositories.outputs.repositories }}" ' ' '\n' | grep -v '^$' | cut -d / -f 2 | while read -r repository; do
              if curl --fail --retry 16 https://${{ github.repository_owner }}.github.io/"$repository"/dists/stable/Release > /dev/null 2> /dev/null; then
                curl --fail --retry 16 https://${{ github.repository_owner }}.github.io/"$repository"/dists/stable/main/binary-"$arch"/Packages -L 2> /dev/null | sed 's~^Filename: pool/main/~Filename: '"${repository#*/}"'/pool/main/~g' || true
              fi
            done > dists/stable/main/binary-"$arch"/Packages
          done
      - id: check
        run: |
          [ "$(ls dists/stable/main/ | while read -r directory; do echo "${directory#binary-}"; done | xargs -I '{}' git status --porcelain -- dists/stable/main/binary-'{}'/Packages | wc -l)" -gt 0 ] && echo create=true >> "$GITHUB_OUTPUT" || true
      - if: ${{ steps.check.outputs.create == 'true' }}
        uses: plengauer/create-deb-repository@v0.1.0
        with:
          mode: append
          source: ''
      - id: open-pr
        uses: peter-evans/create-pull-request@v8.1.0
        with:
          token: ${{ secrets.ACTIONS_GITHUB_TOKEN }}
          commit-message: "Update Debian Repository"
          base: main
          branch: "update-debian-repository"
          title: "Update Debian Repository"
          body: |
            (this PR is automatically generated)
          delete-branch: true
      - if: steps.open-pr.outputs.pull-request-number != null
        run: sleep 60 # make sure PR state is updated and API can catch up
      - if: steps.open-pr.outputs.pull-request-number != null
        env:
          GH_TOKEN: ${{ secrets.ACTIONS_GITHUB_TOKEN }}
        run: gh pr merge --squash --auto ${{ steps.open-pr.outputs.pull-request-number }}
