name: 'Update Package Repository'

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - main
    paths:
      - .github/workflows/update_deb_repository.yml

concurrency:
  group: update-package-repository

jobs:

  update:
    runs-on: ubuntu-latest
    permissions:
      actions: read
    steps:
      - uses: plengauer/opentelemetry-github/actions/instrument/job@909c7153cce2c6ef916f4fde6958886d9d65af03 # v5.55.0
        env:
          OTEL_EXPORTER_OTLP_ENDPOINT: ${{ secrets.OTEL_EXPORTER_OTLP_ENDPOINT }}
          OTEL_EXPORTER_OTLP_HEADERS: ${{ secrets.OTEL_EXPORTER_OTLP_HEADERS }}
        with:
          secrets_to_redact: '["${{ github.token }}","${{ secrets.ACTIONS_GITHUB_TOKEN }}"]'
      - id: list-repositories
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh api /users/${{ github.repository_owner }}/repos --paginate | jq '.[] | select(.visibility == "public" and .owner.login == "${{ github.repository_owner }}") | .owner.login + "/" + .name | select(. != "${{ github.repository }}")' -r | tr '\n' ' ' | xargs -0 -I '{}' echo repositories='{}' >> "$GITHUB_OUTPUT"
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - run: rm -rf dists/stable/main/binary-*
      - run: |
          tr <<< "${{ steps.list-repositories.outputs.repositories }}" ' ' '\n' | grep -v '^$' | cut -d / -f 2 | while read -r repository; do
            curl --fail --retry 16 https://${{ github.repository_owner }}.github.io/"$repository"/dists/stable/Release 2> /dev/null | grep -E '/Packages$' | cut -d ' ' -f 4 | cut -d / -f 2 | cut -d - -f 2 | sort -u | while read -r arch; do
              mkdir -p dists/stable/main/binary-"$arch"
              curl --fail --retry 16 https://${{ github.repository_owner }}.github.io/"$repository"/dists/stable/main/binary-"$arch"/Packages -L | sed 's~^Filename: pool/main/~Filename: '"${repository#*/}"'/pool/main/~g' >> dists/stable/main/binary-"$arch"/Packages
            done
          done
      - id: check
        run: |
          [ "$(ls dists/stable/main/ | while read -r directory; do echo "${directory#binary-}"; done | xargs -I '{}' git status --porcelain -- dists/stable/main/binary-'{}'/Packages | wc -l)" -gt 0 ] && echo create=true >> "$GITHUB_OUTPUT" || true
      - # if: ${{ steps.check.outputs.create == 'true' }}
        uses: plengauer/create-package-repository@2d3d79460d6c590c0f4e0dac6419d268c7d7a83d # v1.0.0
        with:
          mode: append
          source: ''
      - id: open-pr
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          token: ${{ secrets.ACTIONS_GITHUB_TOKEN }}
          commit-message: "Update Debian Repository"
          base: main
          branch: "update-debian-repository"
          title: "Update Debian Repository"
          body: |
            (this PR is automatically generated)
          delete-branch: true
      - if: steps.open-pr.outputs.pull-request-number != null
        run: sleep 60 # make sure PR state is updated and API can catch up
      - if: steps.open-pr.outputs.pull-request-number != null
        env:
          GH_TOKEN: ${{ secrets.ACTIONS_GITHUB_TOKEN }}
        run: gh pr merge --squash --auto ${{ steps.open-pr.outputs.pull-request-number }}
